useDotenv: true
org: ${env:ORG}
service: notes-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  profile: ${env:PROFILE}
  iam:
    role: ${env:IAM_Role}

functions:
  signup:
    handler: auth/signup.handler
    events:
      - http:
          path: auth/signup
          method: post

  signin:
    handler: auth/signin.handler
    events:
      - http:
          path: auth/signin
          method: post

  createNote:
    handler: functions/createNote.handler
    events:
      - http:
          path: notes
          method: post

  listNotes:
    handler: functions/listNotes.handler
    events:
      - http:
          path: notes
          method: get

  getNote:
    handler: functions/getNote.handler
    events:
      - http:
          path: notes/{id}
          method: get

  updateNote:
    handler: functions/updateNote.handler
    events:
      - http:
          path: notes/{id}
          method: put

  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          path: notes/{id}
          method: delete

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-table
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
